gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/88 > item_88.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/89 > item_89.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/90 > item_90.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/91 > item_91.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/92 > item_92.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/93 > item_93.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/94 > item_94.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/95 > item_95.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/96 > item_96.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/97 > item_97.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/98 > item_98.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/99 > item_99.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/100 > item_100.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/101 > item_101.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/102 > item_102.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/103 > item_103.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/104 > item_104.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/105 > item_105.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/106 > item_106.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/109 > item_109.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/110 > item_110.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/111 > item_111.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/112 > item_112.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/113 > item_113.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/114 > item_114.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/115 > item_115.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/116 > item_116.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/117 > item_117.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/118 > item_118.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/119 > item_119.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/120 > item_120.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/121 > item_121.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/122 > item_122.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/123 > item_123.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/124 > item_124.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/125 > item_125.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/126 > item_126.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/127 > item_127.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/128 > item_128.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/129 > item_129.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/130 > item_130.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/131 > item_131.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/132 > item_132.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/133 > item_133.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/134 > item_134.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/135 > item_135.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/136 > item_136.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/137 > item_137.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/138 > item_138.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/139 > item_139.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/140 > item_140.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/141 > item_141.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/142 > item_142.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/143 > item_143.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/173 > item_173.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/174 > item_174.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/176 > item_176.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/321 > item_321.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/335 > item_335.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/336 > item_336.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/337 > item_337.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/338 > item_338.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/339 > item_339.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/340 > item_340.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/341 > item_341.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/342 > item_342.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/343 > item_343.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/344 > item_344.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/345 > item_345.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/346 > item_346.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/347 > item_347.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/348 > item_348.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/349 > item_349.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/350 > item_350.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/351 > item_351.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/352 > item_352.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/353 > item_353.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/354 > item_354.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/355 > item_355.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/356 > item_356.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/357 > item_357.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/358 > item_358.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/359 > item_359.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/360 > item_360.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/361 > item_361.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/362 > item_362.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/363 > item_363.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/364 > item_364.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/365 > item_365.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/366 > item_366.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/367 > item_367.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/368 > item_368.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/369 > item_369.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/370 > item_370.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/371 > item_371.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/372 > item_372.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/373 > item_373.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/374 > item_374.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/375 > item_375.json 
gh project item-add 2 --owner Menschlichkeit-Osterreich --url https://github.com/Menschlichkeit-Osterreich/menschlichkeit-oesterreich/issues/376 > item_376.json 
